version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: prime_api
    restart: always
    ports:
      - "8081:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: prime_db
    restart: always
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prime_db
